healthz_readiness:
  path: /healthz/ready
  controller: MCEikens\SymfonyKubernetesHealthzCheck\Controller\Healthz\ReadinessProbeController
  methods: GET
healthz_liveness:
  path: /healthz/live
  controller: MCEikens\SymfonyKubernetesHealthzCheck\Controller\Healthz\LivenessProbeController
  methods: GET
